export const wordsEN  = 
["time", "person", "way", "day", "man", "year", "government", "company", "hand", "part", 
"place", "case", "group", "problem", "fact", "eye", "friend", "charge", "home", "question",
"business", "power", "change", "country", "child", "house", "point", "government", "company",
"hand", "part", "place", "case", "group", "problem", "fact", "eye", "friend", "charge", "home",
"question", "business", "power", "change", "country", "child", "house", "point", "back", "work",
"high", "line", "end", "member", "law", "air", "car", "food", "water", "room", "friend", "mother",
"money", "book", "reason", "name", "word", "number", "fact", "woman", "place", "side", "kind", 
"head", "country", "tax", "gold", "method", "system", "theory", "service", "word", "art", "picture",
"man", "gentleman", "lady", "love", "hate", "war", "peace", "freedom", "idea", "mind", "power", "world",
"morning", "evening", "night", "day", "week", "month", "year", "decade", "century", "past", "present",
"future", "science", "technology", "information", "education", "language", "culture", "history",
"nature", "environment", "industry", "market", "money", "economy", "society", "government", "politics",
"media", "communication", "internet", "computer", "software", "hardware", "network", "medicine",
"health", "doctor", "hospital", "patient", "disease", "treatment", "research", "discovery", "space",
"planet", "star", "galaxy", "universe", "earth", "nature", "animal", "plant", "evolution", "biology",
"chemistry", "physics", "mathematics", "language", "literature", "art", "music", "film", "television",
"sports", "game", "entertainment", "travel", "adventure", "experience", "emotion", "feeling", "thought",
"mind", "consciousness", "spirit", "soul", "religion", "faith", "belief", "morality", "ethics",
"philosophy", "mind", "body", "health", "wellness", "fitness", "exercise", "nutrition", "food",
"drink", "sleep", "rest", "energy", "emotion", "feeling", "relationship", "family", "friendship",
"love", "marriage", "parent", "child", "sibling", "communication", "conversation", "speech", "language",
"writing", "reading", "knowledge", "learning", "education", "school", "teacher", "student", "class",
"lesson", "skill", "talent", "ability", "intelligence", "wisdom", "success", "failure", "achievement",
"goal", "dream", "ambition", "passion", "purpose", "meaning", "life", "run", "jump", "talk", "sing",
"dance", "play", "work", "read", "write", "listen", "speak", "think", "create", "explore", "discover",
"travel", "drive", "fly", "swim", "climb", "eat", "drink", "sleep", "dream", "love", "hate", "fight",
"win", "lose", "smile", "laugh", "cry", "feel", "learn", "teach", "help", "give", "take", "grow",
"change", "imagine", "believe", "achieve", "inspire", "motivate", "encourage", "support", "challenge",
"adapt", "survive", "create", "innovate", "succeed", "fail", "accept", "explore", "dream", "enjoy",
"appreciate", "understand", "communicate", "connect", "relax", "reflect", "remember", "forget",
"forgive", "move", "stay", "begin", "end", "start", "finish", "live", "experience", "embrace",
"celebrate", "improve", "discover", "express", "inspire", "motivate", "encourage", "support", "challenge",
"adapt", "survive", "create", "innovate", "succeed", "fail", "accept", "explore", "dream", "enjoy",
"appreciate", "understand", "communicate", "connect", "relax", "reflect", "remember", "forget",
"forgive", "move", "stay", "begin", "end", "start", "finish", "live", "experience", "embrace",
"celebrate", "improve", "discover", "express", "inspire", "motivate", "encourage", "support", "challenge",
"adapt", "survive", "create", "innovate", "succeed", "fail", "accept", "explore", "dream", "enjoy",
"appreciate", "understand", "Stella", "Oliver", "Aria", "Henry", "Lily", "Harper",
"Noah", "Grace", "Jackson", "Ethan", "James", "Emily", "Michael", "Sophia", "William", "Olivia",
"Benjamin", "Emma", "Alexander", "Piter"];

export const wordsPT =
["tempo", "pessoa", "caminho", "dia", "homem", "ano", "governo", "empresa", "mão", "parte",
"lugar", "caso", "grupo", "problema", "fato", "olho", "amigo", "carga", "casa", "questão",
"negócio", "poder", "mudança", "país", "criança", "casa", "ponto", "governo", "empresa", "mão",
"parte", "lugar", "caso", "grupo", "problema", "fato", "olho", "amigo", "carga", "casa", "questão",
"negócio", "poder", "mudança", "país", "criança", "casa", "ponto", "trás", "trabalhar", "alto",
"linha", "fim", "membro", "lei", "ar", "carro", "comida", "água", "quarto", "amigo", "mãe",
"dinheiro", "livro", "razão", "nome", "palavra", "número", "fato", "mulher", "lugar", "lado",
"tipo", "cabeça", "país", "imposto", "ouro", "método", "sistema", "teoria", "serviço", "palavra",
"arte", "imagem", "homem", "cavalheiro", "dama", "amor", "odiar", "guerra", "paz", "liberdade",
"ideia", "mente", "poder", "mundo", "manhã", "tarde", "noite", "dia", "semana", "mês", "ano",
"década", "século", "passado", "presente", "futuro", "ciência", "tecnologia", "informação",
"educação", "língua", "cultura", "história", "natureza", "ambiente", "indústria", "mercado",
"dinheiro", "economia", "sociedade", "governo", "política", "mídia", "comunicação", "internet",
"computador", "software", "hardware", "rede", "medicina", "saúde", "médico", "hospital", "paciente",
"doença", "tratamento", "pesquisa", "descoberta", "espaço", "planeta", "estrela", "galáxia",
"universo", "terra", "natureza", "animal", "planta", "evolução", "biologia", "química", "física",
"matemática", "língua", "literatura", "arte", "música", "filme", "televisão", "esportes", "jogo",
"entretenimento", "viagem", "aventura", "experiência", "emoção", "sentimento", "pensamento",
"mente", "consciência", "espírito", "alma", "religião", "fé", "crença", "moralidade", "ética",
"filosofia", "mente", "corpo", "saúde", "bem-estar", "fitness", "exercício", "nutrição", "comida",
"bebida", "dormir", "descansar", "sonho", "amor", "odiar", "lutar", "ganhar", "perder", "sorrir",
"rir", "chorar", "sentir", "aprender", "ensinar", "ajudar", "dar", "levar", "crescer", "mudar",
"imaginar", "acreditar", "conseguir", "inspirar", "motivar", "encorajar", "apoiar", "desafiar",
"adaptar", "sobreviver", "criar", "inovar", "sucesso", "falhar", "aceitar", "explorar",
"sonhar", "aproveitar", "apreciar", "entender", "comunicar", "conectar", "relaxar", "refletir",
"lembrar", "esquecer", "perdoar", "mover", "ficar", "começar", "terminar", "viver", "experimentar",
"abraçar", "celebrar", "melhorar", "descobrir", "expressar", "inspirar", "motivar", "encorajar",
"apoiar", "desafiar", "adaptar", "sobreviver", "criar", "inovar", "sucesso", "falhar", "aceitar",
"explorar", "sonhar", "aproveitar", "Vitória", "Matheus", "Larissa", "Rafael", "Laura",
"Leonardo", "Gabrielle", "Daniel", "Mariana", "Rodrigo", "João", "Maria", "Pedro", "Ana",
"Lucas", "Sofia", "Miguel", "Beatriz", "Guilherme", "Isabela"];

export const wordsES = 
["tiempo", "persona", "camino", "día", "hombre", "año", "gobierno", "empresa", "mano", "parte",
"lugar", "caso", "grupo", "problema", "hecho", "ojo", "amigo", "carga", "casa", "pregunta",
"negocio", "poder", "cambio", "país", "niño", "casa", "punto", "gobierno", "empresa", "mano",
"parte", "lugar", "caso", "grupo", "problema", "hecho", "ojo", "amigo", "carga", "casa", "pregunta",
"negocio", "poder", "cambio", "país", "niño", "casa", "punto", "atrás", "trabajar", "alto",
"línea", "fin", "miembro", "ley", "aire", "coche", "comida", "agua", "cuarto", "amigo", "madre",
"dinero", "libro", "razón", "nombre", "palabra", "número", "hecho", "mujer", "lugar", "lado",
"tipo", "cabeza", "país", "impuesto", "oro", "método", "sistema", "teoría", "servicio", "palabra",
"arte", "imagen", "hombre", "caballero", "dama", "amor", "odiar", "guerra", "paz", "libertad",
"idea", "mente", "poder", "mundo", "mañana", "tarde", "noche", "día", "semana", "mes", "año",
"década", "siglo", "pasado", "presente", "futuro", "ciencia", "tecnología", "información",
"educación", "lengua", "cultura", "historia", "naturaleza", "ambiente", "industria", "mercado",
"dinero", "economía", "sociedad", "gobierno", "política", "medios", "comunicación", "internet",
"computadora", "software", "hardware", "red", "medicina", "salud", "médico", "hospital", "paciente",
"enfermedad", "tratamiento", "investigación", "descubrimiento", "espacio", "planeta", "estrella",
"galaxia", "universo", "tierra", "naturaleza", "animal", "planta", "evolución", "biología", "química",
"física", "matemáticas", "lengua", "literatura", "arte", "música", "película", "televisión", "deporte",
"juego", "entretenimiento", "viaje", "aventura", "experiencia", "emoción", "sentimiento", "pensamiento",
"mente", "conciencia", "espíritu", "alma", "religión", "fe", "creencia", "moralidad", "ética", "filosofía",
"cuerpo", "salud", "bienestar", "fitness", "ejercicio", "nutrición", "comida", "bebida", "sueño", "descanso",
"energía", "emoción", "sentimiento", "relación", "familia", "amistad", "amor", "matrimonio", "padre",
"hijo", "hermano", "comunicación", "conversación", "discurso", "lengua", "escritura", "lectura",
"conocimiento", "aprendizaje", "educación", "escuela", "profesor", "alumno", "clase", "lección",
"habilidad", "talento", "habilidad", "inteligencia", "sabiduría", "éxito", "fracaso", "logro", "meta",
"sueño", "ambición", "pasión", "propósito", "significado", "vida", "correr", "saltar", "hablar", "cantar",
"bailar", "jugar", "trabajar", "leer", "escribir", "escuchar", "hablar", "pensar", "crear", "explorar",
"descubrir", "viajar", "conducir", "volar", "nadar", "escalar", "comer", "beber", "dormir", "soñar",
"amar", "odiar", "pelear", "ganar", "perder", "sonreír", "reír", "llorar", "sentir", "aprender",
"enseñar", "ayudar", "dar", "tomar", "crecer", "cambiar", "imaginar", "creer", "lograr", "inspirar",
"motivar", "alentar", "apoyar", "desafiar", "adaptar", "sobrevivir", "crear", "innovar", "éxito",
"fracasar", "aceptar", "explorar", "soñar", "disfrutar", "apreciar", "entender", "comunicar", "conectar",
"relajarse", "reflejar", "recordar", "olvidar", "perdonar", "mover", "quedarse", "empezar", "terminar",
"vivir", "experimentar", "abrazar", "celebrar", "mejorar", "descubrir", "expresar", "inspirar", "motivar",
"alentar", "apoyar", "desafiar", "adaptar", "sobrevivir", "crear", "innovar", "éxito", "fracasar",
"aceptar", "explorar", "Martina", "Javier", "Isidora", "Emilio", "Luna", "Matías", "Natalia",
"Esteban", "Valeria", "Renato", "Gabriela", "Alejandro", "Sofia", "Mateo", "Valentina", "Diego",
"Isabella", "Javier", "Camila", "Carlos"];



